spring.application.name=erp-server

# 기본 실행 환경을 local 프로필로 지정
# spring.profiles.active=local
# 별도 프로필이 지정되지 않은 일반 실행에서는 local 프로필을 기본으로 사용
spring.profiles.default=local


# =========================
#		JPA
# =========================
# validate: Entity와 실제 DB 테이블 구조가 일치하는지 서버 시작 시 검증
# 테이블을 자동 생성하거나 수정하지 않음
spring.jpa.hibernate.ddl-auto=validate

# 실행되는 SQL을 콘솔에 출력
spring.jpa.show-sql=true

# 출력되는 SQL을 보기 좋게 줄바꿈/정렬
spring.jpa.properties.hibernate.format_sql=true

# =========================
#       Logging
# =========================
# 로그 출력 시 현재 요청의 traceId(MDC 값)와 로그 레벨을 함께 표시한다.
logging.pattern.level=traceId:%X{traceId} %5p

# 서버 로그를 logs/erp-server.log 파일에도 저장한다.
logging.file.name=logs/erp-server.log