/* =========================================================
   01_sequences.sql
   ERP Oracle Sequence 생성
   ========================================================= */


/* =========================================================
   1. 공통·기준정보
   ========================================================= */

CREATE SEQUENCE SEQ_APP_USER
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_CUSTOMER
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_CUSTOMER_TRADE_STATUS_HISTORY
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_SUPPLIER
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_ITEM
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_SUPPLIER_ITEM
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_WAREHOUSE
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_WAREHOUSE_ITEM
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;


/* =========================================================
   2. 구매
   ========================================================= */

CREATE SEQUENCE SEQ_PURCHASE_ORDER
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_PURCHASE_ORDER_ITEM
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_PURCHASE_ORDER_EMAIL_HISTORY
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_RECEIPT
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_RECEIPT_ITEM
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_RECEIPT_LOT
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_PURCHASE_RETURN
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_PURCHASE_RETURN_ITEM
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;


/* =========================================================
   3. 판매
   ========================================================= */

CREATE SEQUENCE SEQ_SALES_ORDER
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_SALES_ORDER_ITEM
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_SHIPMENT
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_SHIPMENT_LOT
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_DELIVERY_NOTE
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_CUSTOMER_RETURN
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_CUSTOMER_RETURN_ITEM
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;


/* =========================================================
   4. 재고
   ========================================================= */

CREATE SEQUENCE SEQ_INVENTORY_LOT
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_LOT_STATUS_HISTORY
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_STOCK_MOVEMENT
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_STOCKTAKE
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_STOCKTAKE_ITEM
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_STOCK_ADJUSTMENT
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;


/* =========================================================
   5. 정산
   ========================================================= */

CREATE SEQUENCE SEQ_VOUCHER
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_VOUCHER_ITEM
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_PAYMENT
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_PAYMENT_ALLOCATION
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;


/* =========================================================
   6. 업무 식별 코드
   PK Sequence와 별도로 관리
   ========================================================= */

CREATE SEQUENCE SEQ_CUSTOMER_CODE
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_SUPPLIER_CODE
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_ITEM_CODE
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_WAREHOUSE_CODE
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_INTERNAL_LOT_CODE
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;